import "file:///home/runner/Erika-Farmer/src/commands/mod.ts#0";
import "file:///home/runner/Erika-Farmer/src/events/interactionCreate.ts#1";
import "file:///home/runner/Erika-Farmer/src/events/ready.ts#1";
import "file:///home/runner/Erika-Farmer/src/commands/api/inspire.ts#2";
import "file:///home/runner/Erika-Farmer/src/commands/api/kot.ts#2";
import "file:///home/runner/Erika-Farmer/src/commands/api/wada.ts#2";
import "file:///home/runner/Erika-Farmer/src/commands/memories.ts#3";
import "file:///home/runner/Erika-Farmer/src/commands/anime.ts#3";
import "file:///home/runner/Erika-Farmer/src/commands/hug.ts#3";